In [1]:
import numpy as np
import xarray as xr
import pandas as pd
import netCDF4
import glob
import os

In [2]:
df=pd.read_csv('claire.csv')
df

key_CLM5PPE                         param   minmax include person_to_run  \
0     OAAT0000                       default  default     yes      czarakas   
1     OAAT0013                       rhosnir      min     yes      czarakas   
2     OAAT0014                       rhosnir      max     yes      czarakas   
3     OAAT0035                         d_max      min     yes      czarakas   
4     OAAT0036                         d_max      max     yes      czarakas   
5     OAAT0037        frac_sat_soil_dsl_init      min     yes      czarakas   
6     OAAT0038        frac_sat_soil_dsl_init      max     yes      czarakas   
7     OAAT0072  maximum_leaf_wetted_fraction      min     yes      czarakas   
8     OAAT0073  maximum_leaf_wetted_fraction      max     yes      czarakas   
9     OAAT0076                           fff      min     yes      czarakas   
10    OAAT0077                           fff      max     yes      czarakas   
11    OAAT0098     upplim_destruct_metamorph      min     yes      czarakas   
12    OAAT0099     upplim_destruct_metamorph      max     yes      czarakas   
13    OAAT0118                   medlynslope      max     yes      czarakas   
14    OAAT0119               medlynintercept      min     yes      czarakas   
15    OAAT0137                    tpu25ratio      min     yes      czarakas   
16    OAAT0138                    tpu25ratio      max     yes      czarakas   
17    OAAT0146                        jmaxb0      max     yes        amyliu   
18    OAAT0147                        jmaxb1      min     yes        amyliu   
19    OAAT0148                        jmaxb1      max     yes        amyliu   
20    OAAT0159                          kmax      min     yes        amyliu   
21    OAAT0160                          kmax      max     yes        amyliu   
22    OAAT0171                         nstem      min     yes        amyliu   
23    OAAT0172                         nstem      max     yes        amyliu   
24    OAAT0355                         lmrha      min     yes        amyliu   
25    OAAT0356                         lmrha      max     yes        amyliu   
26    OAAT0400                   medlynslope      min     yes        amyliu   
27    OAAT0403                        jmaxb0      min     yes        amyliu   
28    OAAT0413               medlynintercept      max     yes        amyliu   
29    OAAT0458                       sand_pf      min     yes        amyliu   
30    OAAT0459                       sand_pf      max     yes        amyliu   
31    OAAT0023                          z0mr      min     yes      czarakas   
32    OAAT0024                          z0mr      max     yes      czarakas   
33    OAAT0033                          zsno      min     yes      czarakas   
34    OAAT0034                          zsno      max     yes      czarakas   
35    OAAT0042                 zetamaxstable      min     yes      czarakas   
36    OAAT0043                 zetamaxstable      max     yes      czarakas   

    round_to_run key_coupledPPE key_landonlyPPE  
0              1       COUP0000        OFFL0000  
1              1       COUP0001        OFFL0001  
2              1       COUP0002        OFFL0002  
3              1       COUP0007        OFFL0007  
4              1       COUP0008        OFFL0008  
5              1       COUP0009        OFFL0009  
6              1       COUP0010        OFFL0010  
7              1       COUP0013        OFFL0013  
8              1       COUP0014        OFFL0014  
9              1       COUP0015        OFFL0015  
10             1       COUP0016        OFFL0016  
11             1       COUP0017        OFFL0017  
12             1       COUP0018        OFFL0018  
13             1       COUP0019        OFFL0019  
14             1       COUP0020        OFFL0020  
15             1       COUP0021        OFFL0021  
16             1       COUP0022        OFFL0022  
17             1       COUP0023        OFFL0023  
18             1       COUP0024        OFFL0024  


In [10]:
pdir='/glade/u/home/djk2120/mapp_droughts/cce/params/paramfiles/'
basefile=pdir+'base.nc'

In [12]:
v='frac_sat_soil_dsl_init'
ix=df.param==v
ps=df.key_CLM5PPE[ix].values
for p in ps:
    nextnum = 1+int(sorted(glob.glob(pdir+'p*'))[-1].split('/p')[-1].split('.')[0])
    pfile = pdir+'p'+str(nextnum).zfill(2)+'.nc'
    
    pref = '/glade/campaign/asp/djk2120/PPEn11/paramfiles/'+p+'.nc'
    ## CREATE and EDIT the new paramfile
    cmd = 'cp '+basefile+' '+pfile
    os.system(cmd)
    cmd = 'chmod 644 '+pfile
    os.system(cmd)

    dset = netCDF4.Dataset(pfile,'r+')
    x = xr.open_dataset(pref)[v]
    dset[v][:] = x
    dset.close()

In [5]:
xr.open_dataset(pref)[v]

<xarray.DataArray 'kmax' (segment: 4, pft: 79)>
array([[0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08],
       [0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08],
       [0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08],
       [0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08]])
Coordinates:
    pftname  (pft) |S40 ...
  * segment  (segment) |S40 b'sunlit                                  ' ... b...
Dimensions without coordinates: pft
Attributes:
    units:      mm h2o (transpired)/mm h2o (water potential gradient)/sec
    long_name:  plant segment max conductance

In [6]:
xr.open_dataset(pfile)[v]

<xarray.DataArray 'kmax' (segment: 4, pft: 79)>
array([[0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08],
       [0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08],
       [0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08],
       [0.0e+00, 3.8e-08, 3.4e-08, ..., 3.1e-08, 3.1e-08, 3.1e-08]])
Coordinates:
    pftname  (pft) |S40 ...
  * segment  (segment) |S40 b'sunlit                                  ' ... b...
Dimensions without coordinates: pft
Attributes:
    units:      mm h2o (transpired)/mm h2o (water potential gradient)/sec
    long_name:  plant segment max conductance

In [7]:
xr.open_dataset(basefile)[v]

<xarray.DataArray 'kmax' (segment: 4, pft: 79)>
array([[0.e+00, 2.e-08, 2.e-08, ..., 2.e-08, 2.e-08, 2.e-08],
       [0.e+00, 2.e-08, 2.e-08, ..., 2.e-08, 2.e-08, 2.e-08],
       [0.e+00, 2.e-08, 2.e-08, ..., 2.e-08, 2.e-08, 2.e-08],
       [0.e+00, 2.e-08, 2.e-08, ..., 2.e-08, 2.e-08, 2.e-08]])
Coordinates:
    pftname  (pft) |S40 ...
  * segment  (segment) |S40 b'sunlit                                  ' ... b...
Dimensions without coordinates: pft
Attributes:
    units:      mm h2o (transpired)/mm h2o (water potential gradient)/sec
    long_name:  plant segment max conductance